# 자동 리플렉션 설정

# 기본 파일 경로
input_file: "tasks.json"
output_file: "tasks.reflected.json"
report_file: "reports/tasks_reflect_report.md"

# 파일 감시 설정
watch_directories:
  - "."           # 현재 디렉토리
  - "docs"        # 문서 디렉토리
  - "src"         # 소스 디렉토리
  - "tools"       # 도구 디렉토리

watch_extensions:
  - ".json"       # JSON 파일
  - ".md"         # Markdown 파일
  - ".yaml"       # YAML 파일
  - ".yml"        # YAML 파일
  - ".py"         # Python 파일

# 스케줄 설정
reflection_interval: 300  # 5분 (초)

# 재시도 설정
max_retries: 3
retry_delay: 5

# 웹훅 설정
webhook_port: 8080
webhook_endpoints:
  - "/reflect"
  - "/update"
  - "/trigger"

# 알림 설정
notification_channels:
  - "console"     # 콘솔 출력
  - "log"         # 로그 파일
  # - "webhook:http://localhost:9000/notify"  # 웹훅 알림 (예시)
  # - "email:admin@example.com"               # 이메일 알림 (예시)

# 고급 설정
advanced:
  # 파일 변경 감지
  file_watching:
    debounce_time: 2.0        # 디바운스 시간 (초)
    hash_check: true          # 해시 기반 변경 감지
    recursive: true           # 재귀적 디렉토리 감시
    
  # 성능 최적화
  performance:
    batch_processing: false   # 배치 처리 (미구현)
    parallel_reflection: false # 병렬 리플렉션 (미구현)
    cache_reflection: true    # 리플렉션 결과 캐싱
    
  # 보안 설정
  security:
    allowed_directories:      # 허용된 디렉토리
      - "."
      - "docs"
      - "src"
      - "tools"
    blocked_extensions:       # 차단된 확장자
      - ".exe"
      - ".bat"
      - ".sh"
    max_file_size: 10485760   # 최대 파일 크기 (10MB)

# 로깅 설정
logging:
  level: "INFO"
  file: "auto_reflection.log"
  max_size: 10485760         # 10MB
  backup_count: 5
  format: "%(asctime)s - %(levelname)s - %(message)s"

# 통계 및 모니터링
monitoring:
  # 통계 수집
  collect_statistics: true
  statistics_interval: 3600  # 1시간마다 통계 수집
  
  # 헬스 체크
  health_check:
    enabled: true
    interval: 60             # 1분마다 헬스 체크
    timeout: 30              # 헬스 체크 타임아웃
    
  # 성능 메트릭
  metrics:
    - "reflection_count"
    - "success_rate"
    - "average_duration"
    - "error_rate"
    - "uptime"

# 통합 설정
integration:
  # Cursor IDE 통합
  cursor_integration:
    enabled: true
    auto_reload: true        # 자동 리로드
    
  # MCP 통합
  mcp_integration:
    enabled: false           # MCP 통합 비활성화
    mcp_server: "shrimp"
    
  # CI/CD 통합
  cicd_integration:
    enabled: false           # CI/CD 통합 비활성화
    webhook_url: ""
    auth_token: ""

# 개발 및 디버깅
development:
  debug_mode: false          # 디버그 모드
  verbose_logging: false     # 상세 로깅
  dry_run: false            # 실제 실행 없이 테스트
  
  # 테스트 설정
  test_mode:
    enabled: false
    test_files: []
    mock_reflection: false

# 환경별 설정
environments:
  development:
    logging:
      level: "DEBUG"
    webhook_port: 8080
    reflection_interval: 60   # 1분
    
  production:
    logging:
      level: "INFO"
    webhook_port: 80
    reflection_interval: 300  # 5분
    notification_channels:
      - "console"
      - "log"
      - "webhook:https://monitoring.example.com/alerts"
      
  testing:
    logging:
      level: "DEBUG"
    webhook_port: 8081
    reflection_interval: 10   # 10초
    watch_directories:
      - "test"
      - "tests"
