# 대기업용 우선순위 실행 설정 (안정성 우선, 대규모 리소스)

execution:
  # 기본 실행 전략 (안정성 우선)
  default_strategy: "dependency"  # 의존성 기반 안전 실행
  
  # 병렬 실행 설정 (대규모 리소스)
  parallel:
    enabled: true
    max_workers: 8               # 다중 워커
    timeout_per_task: 600        # 10분 (충분한 시간)
    
  # 재시도 설정 (안정성 중시)
  retry:
    max_attempts: 5              # 충분한 재시도
    backoff_factor: 2.0
    max_delay: 300               # 5분

# 태스크 타입별 설정 (엔터프라이즈 우선순위)
task_types:
  code:
    command_template: "cursor agent --apply=ask --rules \"{title}\" --compliance-check"
    can_parallel: false
    priority: 1
    estimated_duration: 300      # 5분 (코드 리뷰 포함)
    compliance_required: true
    
  config:
    command_template: "echo \"Config: {title}\" --audit-trail"
    can_parallel: true
    priority: 2
    estimated_duration: 180      # 3분
    audit_required: true
    
  test:
    command_template: "python -m pytest {module} -v --coverage --junitxml=results.xml"
    can_parallel: true
    priority: 3
    estimated_duration: 240      # 4분 (커버리지 포함)
    coverage_required: true
    
  docs:
    command_template: "echo \"Documentation: {title}\" --review"
    can_parallel: true
    priority: 4
    estimated_duration: 120      # 2분 (리뷰 포함)
    review_required: true
    
  security:
    command_template: "security-scan --target {module}"
    can_parallel: true
    priority: 1                  # 보안 최우선
    estimated_duration: 180
    mandatory: true

# 복잡도 기반 우선순위
complexity_weights:
  low: 0.8                      # 낮은 복잡도도 중요
  medium: 1.2
  high: 1.8
  critical: 2.5

# 실행 전략별 설정
strategies:
  dependency:
    enabled: true               # 기본 전략
    max_depth: 10               # 깊은 의존성 허용
    prefer_parallel: true
    
  complexity:
    enabled: true
    complexity_threshold: 1.5
    prefer_sequential: true     # 복잡한 작업은 순차 실행
    
  efficiency:
    enabled: false              # 효율성보다 안정성 우선
    time_weight: 0.3
    resource_weight: 0.7

# 팀 설정
team:
  size: "large"                 # 대규모 팀
  experience_level: "senior"    # 시니어 개발자
  working_hours: "24/7"         # 24시간 운영
  timezone: "UTC"               # 글로벌 팀

# 알림 설정
notifications:
  slack:
    enabled: true
    channels:                   # 다중 채널
      - "#dev-alerts"
      - "#security-alerts"
      - "#performance-alerts"
    mention_on_failure: true
    escalation: true            # 에스컬레이션
    
  email:
    enabled: true               # 이메일 활성화
    recipients:
      - "dev-team@company.com"
      - "security-team@company.com"
      - "management@company.com"
    
  console:
    enabled: true
    verbose: false              # 간결한 로그
    
  pagerduty:
    enabled: true               # PagerDuty 연동
    escalation_policy: "dev-team"

# 성능 설정
performance:
  max_memory_usage: 4096        # 4GB 제한
  max_cpu_usage: 80             # 80% 제한
  disk_space_limit: 10240       # 10GB 제한
  
# 엔터프라이즈 환경
enterprise:
  compliance: true              # 컴플라이언스 필수
  audit_trail: true             # 감사 추적
  security_scan: true           # 보안 스캔
  code_review: true             # 코드 리뷰 필수
  
# 모니터링 설정
monitoring:
  enabled: true
  metrics:
    - "execution_time"
    - "success_rate"
    - "resource_usage"
    - "error_rate"
  
  alerts:
    - "high_failure_rate"
    - "resource_exhaustion"
    - "security_violation"
    - "compliance_failure"

# 백업 및 복구
backup:
  enabled: true
  interval: "daily"
  retention_days: 90
  cloud_storage: true

# 보안 설정
security:
  encryption: true
  access_control: true
  vulnerability_scan: true
  secrets_management: true

# 비용 최적화 (엔터프라이즈)
cost_optimization:
  cloud_provider: "enterprise"
  resource_scaling: "auto"
  reserved_instances: true
  spot_instances: false         # 안정성 우선
